services:
   pattern-lab:
      container_name: pattern-lab-basic-setup__dev
      build:
         context: .
         dockerfile: ./docker/pattern-lab/dockerfile
      image: oktarintentakel/pattern-lab-basic-setup
      volumes:
         - ./project:/project
      working_dir: /project
      ports:
         - 443:443
      environment:
         - TERM=xterm-256color
         - LANG=C.UTF-8
         - NODE_ENV=development
         - ROARR_LOG=true
         - PROJECT=demo
         - ENVIRONMENT=dev
         - HOST=0.0.0.0
         - PORT=443
         - PROTOCOL=https
         - DEVDOMAIN=pattern-lab-basic-setup.local-development.com
      command: bash -c "yarn run start"
