FROM node:20

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y bc ed nano fonts-powerline
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /root
RUN touch build_marker
RUN git clone --recursive https://github.com/andresgongora/synth-shell.git
RUN chmod +x synth-shell/setup.sh
RUN yes | synth-shell/setup.sh

WORKDIR /project
